### ISSUE TITLE
[ISSUE] Software not working with PHP 8.1

### ISSUE THREAD

**Issue by gianlucagiacometti** [WillyXJ/facileManager#558]
Please prefix your issue title with one of the following: [BUG], [ISSUE], [FEATURE REQUEST], [MODULE REQUEST], [OTHER].

Replace everything between stars with current version of your facileManager and module installations:  
fM Version : **4.3.0**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

[Fri Jul 01 09:05:01.968854 2022] [php:error] [pid 1601] [client X.X.X.X:39540] PHP Fatal error:  Uncaught TypeError: sort(): Argument #1 ($array) must be of type array, null given in /web/sites/manager/fm-modules/facile
Manager/variables.inc.php:109\nStack trace:\n#0 /web/sites/manager/fm-modules/facileManager/variables.inc.php(109): sort()\n#1 /web/sites/manager/fm-modules/facileManager/functions.php(71): include('...')\n#
2 /web/sites/manage/config.inc.php(23): require_once('...')\n#3 /web/sites/manager/fm-init.php(58): require_once('...')\n#4 /web/sites/manager/index.php(38): require('...')\n#5 {main}\n  thro
wn in /web/sites/manager/fm-modules/facileManager/variables.inc.php on line 109

If I comment the line or set a if isset && is_array the result is a blank page with just a "1" in output

With PHP 7.4.30 everything works fine

**Comment by drdelaney** [comment]
I got a bit further myself, thanks to a quick note from @gianlucagiacometti , I moved the array declaration to the top of the file.  Had to add another declaration in another file, and had to disable strict mode for mysqli with notes found in here: [https://php.watch/versions/8.1/mysqli-error-mode](url). I am not sure if there are cleaner ways to handle these changes.

This is now the new error I am getting, and am too tired to go further.  Maybe someone else can tag-team a fix.
My changes below.

```[01-Sep-2022 00:04:49 America/Chicago] PHP Fatal error:  Uncaught TypeError: mysqli_free_result(): Argument #1 ($result) must be of type mysqli_result, array given in /opt/dnsadmin/fm-modules/facileManager/c                              lasses/class_logins.php:313
Stack trace:
#0 /opt/dnsadmin/fm-modules/facileManager/classes/class_logins.php(313): mysqli_free_result()
#1 /opt/dnsadmin/fm-init.php(132): fm_login->checkPassword()
#2 /opt/dnsadmin/index.php(38): require('...')
#3 {main}
  thrown in /opt/dnsadmin/fm-modules/facileManager/classes/class_logins.php on line 313
```

The changes I made so far are:
```diff -ur /opt/facileManager/server/ .
Only in .: config.inc.php
diff -ur /opt/facileManager/server/fm-includes/fm-db.php ./fm-includes/fm-db.php
--- /opt/facileManager/server/fm-includes/fm-db.php     2020-11-11 10:12:19.000000000 -0600
+++ ./fm-includes/fm-db.php     2022-09-01 00:01:09.001539271 -0500
@@ -137,6 +137,9 @@

        private function connect($dbuser, $dbpassword, $dbname, $dbhost, $connect_options = 'full check') {
                global $__FM_CONFIG;
+
+               /* Disable MySQLi strict errors */
+               mysqli_report(MYSQLI_REPORT_OFF);

                if ($this->use_mysqli) {
                        $this->dbh = @mysqli_init();
@@ -309,4 +312,4 @@
 }


-?>
\ No newline at end of file
+?>
diff -ur /opt/facileManager/server/fm-modules/facileManager/variables.inc.php ./fm-modules/facileManager/variables.inc.php
--- /opt/facileManager/server/fm-modules/facileManager/variables.inc.php        2020-10-23 18:21:59.000000000 -0500
+++ ./fm-modules/facileManager/variables.inc.php        2022-08-31 23:21:18.038666438 -0500
@@ -40,6 +40,7 @@
 $GLOBALS['FM_URL'] = $GLOBALS['REQUEST_PROTOCOL'] . '://' . $_SERVER['HTTP_HOST'] . $GLOBALS['RELPATH'];

 if (!@is_array($__FM_CONFIG)) $__FM_CONFIG = array();
+if (!@is_array($__FM_CONFIG['logging']['categories'])) $__FM_CONFIG['logging']['categories'] = array();

 /** Images */
 $__FM_CONFIG['icons']['fail']                  = sprintf('<i class="fa fa-times fa-lg fail" alt="%1$s" title="%1$s" aria-hidden="true"></i>', _('Failed'));
diff -ur /opt/facileManager/server/fm-modules/fmDNS/variables.inc.php ./fm-modules/fmDNS/variables.inc.php
--- /opt/facileManager/server/fm-modules/fmDNS/variables.inc.php        2022-06-29 14:54:56.000000000 -0500
+++ ./fm-modules/fmDNS/variables.inc.php        2022-09-01 00:04:05.832652143 -0500
@@ -28,6 +28,7 @@
  */

 if (!@is_array($__FM_CONFIG)) $__FM_CONFIG = array();
+if (!@is_array($__FM_CONFIG['icons'])) $__FM_CONFIG['icons'] = array();

 /** Module Information */
 $__FM_CONFIG['fmDNS'] = array(
```

**Comment by thisisreallyfuckingdumb** [comment]
Signed up just to comment. I recently ran into the same issue(s) after upgrading Ubuntu. I am not a php guru, but here are the changes I made that get things back to a somewhat usable state.

There are still some PHP Warnings but no fatal errors.

```

diff -ur ./fm-includes/fm-db.php /var/www/html/facileManager/fm-includes/fm-db.php
--- ./fm-includes/fm-db.php	2022-09-24 10:13:32.074742609 -0700
+++ /var/www/html/facileManager/fm-includes/fm-db.php	2022-09-24 10:46:17.134849319 -0700
@@ -138,12 +138,15 @@
 	private function connect($dbuser, $dbpassword, $dbname, $dbhost, $connect_options = 'full check') {
 		global $__FM_CONFIG;
 		
+		/* Disable MySQLi strict errors */
+		mysqli_report(MYSQLI_REPORT_OFF);
+
 		if ($this->use_mysqli) {
 			$this->dbh = @mysqli_init();
 
 			/** Set SSL */
 			if (isset($__FM_CONFIG['db']['key'])) {
-				mysqli_ssl_set($this->dbh, $__FM_CONFIG['db']['key'], $__FM_CONFIG['db']['cert'], $__FM_CONFIG['db']['ca'], $__FM_CONFIG['db']['capth'], $__FM_CONFIG['db']['cipher']);
+				mysqli_ssl_set($this->dbh, $__FM_CONFIG['db']['key'], $__FM_CONFIG['db']['cert'], $__FM_CONFIG['db']['ca'], $__FM_CONFIG['db']['capath'], $__FM_CONFIG['db']['cipher']);
 			}
 
 			if (!@mysqli_real_connect($this->dbh, $dbhost, $dbuser, $dbpassword)) {
@@ -309,4 +312,4 @@
 }
 
 
-?>
\ No newline at end of file
+?>
diff -ur ./fm-modules/facileManager/functions.php /var/www/html/facileManager/fm-modules/facileManager/functions.php
--- ./fm-modules/facileManager/functions.php	2022-09-24 10:13:32.082742642 -0700
+++ /var/www/html/facileManager/fm-modules/facileManager/functions.php	2022-09-24 09:59:34.495307916 -0700
@@ -408,7 +408,7 @@
 		</div>
 HTML;
 	
-		if (FM_INCLUDE_SEARCH === true) {
+		if ('FM_INCLUDE_SEARCH' === true) {
 			$search = '<div id="topheadpartright">
 			<a class="single_line search" href="#" title="' . _('Search this page') . '"><i class="fa fa-search fa-lg"></i></a>' .
 				displaySearchForm() . '</div>';
@@ -532,7 +532,7 @@
 		}
 		
 		/** Build submenus */
-		if (!count($classes) && count($filtered_submenu[$slug]) > 1) {
+		if (!count($classes) && count((array)$filtered_submenu[$slug]) > 1) {
 			array_push($classes, 'has-sub');
 			foreach ($filtered_submenu[$slug] as $submenu_array) {
 				if (!empty($submenu_array[0])) {
@@ -865,7 +865,7 @@
 		}
 	} else {
 		for ($i = 0; $i < count($options); $i++) {
-			$selected = ($option_select == $options[$i] || @in_array($options[$i], $option_select)) ? ' selected' : '';
+			$selected = ($option_select == $options[$i] || @in_array($options[$i], (array) $option_select)) ? ' selected' : '';
 			$type_options.="<option$selected>$options[$i]</option>\n";
 		}
 	}
diff -ur ./fm-modules/facileManager/variables.inc.php /var/www/html/facileManager/fm-modules/facileManager/variables.inc.php
--- ./fm-modules/facileManager/variables.inc.php	2022-09-24 10:13:32.094742691 -0700
+++ /var/www/html/facileManager/fm-modules/facileManager/variables.inc.php	2022-09-24 10:08:46.433566231 -0700
@@ -40,6 +40,7 @@
 $GLOBALS['FM_URL'] = $GLOBALS['REQUEST_PROTOCOL'] . '://' . $_SERVER['HTTP_HOST'] . $GLOBALS['RELPATH'];
 
 if (!@is_array($__FM_CONFIG)) $__FM_CONFIG = array();
+if (!@is_array($__FM_CONFIG['logging']['categories'])) $__FM_CONFIG['logging']['categories'] = array();
 
 /** Images */
 $__FM_CONFIG['icons']['fail']			= sprintf('<i class="fa fa-times fa-lg fail" alt="%1$s" title="%1$s" aria-hidden="true"></i>', _('Failed'));
diff -ur ./fm-modules/fmDHCP/classes/class_objects.php /var/www/html/facileManager/fm-modules/fmDHCP/classes/class_objects.php
--- ./fm-modules/fmDHCP/classes/class_objects.php	2022-09-24 10:13:32.094742691 -0700
+++ /var/www/html/facileManager/fm-modules/fmDHCP/classes/class_objects.php	2022-09-24 10:54:39.160923697 -0700
@@ -308,7 +308,7 @@
 		/** Reassigned children */
 		$query = "$sql_start config_parent_id=0 WHERE config_parent_id={$post['config_id']} AND config_is_parent='yes'";
 		$result = $fmdb->query($query);
-		$query = "$sql_start config_parent_id={$post['config_id']} WHERE config_id IN (" . join(',', $post['config_children']) . ")";
+		$query = "$sql_start config_parent_id={$post['config_id']} WHERE config_id IN (" . join(',', (array) $post['config_children']) . ")";
 		$result = $fmdb->query($query);
 
 		return true;
diff -ur ./fm-modules/fmDHCP/variables.inc.php /var/www/html/facileManager/fm-modules/fmDHCP/variables.inc.php
--- ./fm-modules/fmDHCP/variables.inc.php	2022-09-24 10:13:32.098742708 -0700
+++ /var/www/html/facileManager/fm-modules/fmDHCP/variables.inc.php	2022-09-23 21:01:58.919312698 -0700
@@ -28,6 +28,9 @@
  */
 
 if (!@is_array($__FM_CONFIG)) $__FM_CONFIG = array();
+if (!@is_array($__FM_CONFIG['icons'])) $__FM_CONFIG['icons'] = array();
+if (!@is_array($__FM_CONFIG['module']['icons'])) $__FM_CONFIG['module']['icons'] = array();
+if (!@is_array($__FM_CONFIG['clean']['prefixes'])) $__FM_CONFIG['clean']['prefixes'] = array();
 
 /** Module Version */
 $__FM_CONFIG['fmDHCP'] = array(
diff -ur ./fm-modules/fmDNS/classes/class_options.php /var/www/html/facileManager/fm-modules/fmDNS/classes/class_options.php
--- ./fm-modules/fmDNS/classes/class_options.php	2022-09-24 10:13:32.106742741 -0700
+++ /var/www/html/facileManager/fm-modules/fmDNS/classes/class_options.php	2022-09-23 21:46:36.779078258 -0700
@@ -131,8 +131,8 @@
 		$tmp_domain_name = isset($post['domain_id']) ? "\nZone: " . displayFriendlyDomainName(getNameFromID($post['domain_id'], 'fm_' . $__FM_CONFIG['fmDNS']['prefix'] . 'domains', 'domain_', 'domain_id', 'domain_name')) : null;
 
 		include_once(ABSPATH . 'fm-modules/' . $_SESSION['module'] . '/classes/class_acls.php');
-		$cfg_data = (strpos($post['cfg_data'], 'acl_') !== false || strpos($post['cfg_data'], 'key_') !== false || \
-			strpos($post['cfg_data'], 'domain_') !== false || \
+		$cfg_data = (strpos($post['cfg_data'], 'acl_') !== false || strpos($post['cfg_data'], 'key_') !== false || 
+			strpos($post['cfg_data'], 'domain_') !== false || 
 			strpos($post['cfg_data'], 'master_') !== false) ? $fm_dns_acls->parseACL($post['cfg_data']) : $post['cfg_data'];
 		addLogEntry("Added option:\nName: $tmp_name\nValue: $cfg_data\nServer: $tmp_server_name\nView: {$tmp_view_name}{$tmp_domain_name}\nComment: {$post['cfg_comment']}");
 		return true;
@@ -197,8 +197,8 @@
 		$tmp_domain_name = isset($post['domain_id']) ? "\nZone: " . displayFriendlyDomainName(getNameFromID($post['domain_id'], 'fm_' . $__FM_CONFIG['fmDNS']['prefix'] . 'domains', 'domain_', 'domain_id', 'domain_name')) : null;
 
 		include_once(ABSPATH . 'fm-modules/' . $_SESSION['module'] . '/classes/class_acls.php');
-		$cfg_data = (strpos($post['cfg_data'], 'acl_') !== false || strpos($post['cfg_data'], 'key_') !== false || \
-			strpos($post['cfg_data'], 'domain_') !== false || \
+		$cfg_data = (strpos($post['cfg_data'], 'acl_') !== false || strpos($post['cfg_data'], 'key_') !== false || 
+			strpos($post['cfg_data'], 'domain_') !== false || 
 			strpos($post['cfg_data'], 'master_') !== false) ? $fm_dns_acls->parseACL($post['cfg_data']) : $post['cfg_data'];
 		addLogEntry("Updated option '$old_name' to:\nName: {$post['cfg_name']}\nValue: {$cfg_data}\nServer: $tmp_server_name\nView: {$tmp_view_name}{$tmp_domain_name}\nComment: {$post['cfg_comment']}");
 		return true;
@@ -680,9 +680,9 @@
 			include(ABSPATH . 'fm-modules/' . $_SESSION['module'] . '/classes/class_acls.php');
 		}
 		
-		return (strpos($cfg_data, 'acl_') !== false || strpos($cfg_data, 'key_') !== false || \
-			strpos($cfg_data, 'domain_') !== false || strpos($def_type, 'address_match_element') !== false || \
-			strpos($cfg_data, 'master_') !== false || \
+		return (strpos($cfg_data, 'acl_') !== false || strpos($cfg_data, 'key_') !== false || 
+			strpos($cfg_data, 'domain_') !== false || strpos($def_type, 'address_match_element') !== false || 
+			strpos($cfg_data, 'master_') !== false || 
 			strpos($def_type, 'domain_name') !== false) ? $fm_dns_acls->parseACL($cfg_data) : str_replace(',', '; ', $cfg_data);
 	}
 	
diff -ur ./fm-modules/fmDNS/classes/class_zones.php /var/www/html/facileManager/fm-modules/fmDNS/classes/class_zones.php
--- ./fm-modules/fmDNS/classes/class_zones.php	2022-09-24 10:13:32.110742758 -0700
+++ /var/www/html/facileManager/fm-modules/fmDNS/classes/class_zones.php	2022-09-24 10:01:34.483798910 -0700
@@ -861,7 +861,7 @@
 
 			$response = ($response) ? sprintf('<a href="#" class="tooltip-top mini-icon" data-tooltip="%s"><i class="fa fa-question-circle" aria-hidden="true"></i></a>', $response) : null;
 
-			$class = 'class="' . implode(' ', $classes) . '"';
+			$class = 'class="' . implode(' ', (array) $classes) . '"';
 			if (is_array($icons)) {
 				$icons = implode(' ', $icons);
 			}
@@ -1283,7 +1283,7 @@
 		
 		$return = $limited_ids = null;
 		if (isset($user_capabilities)) {
-			$limited_ids = (array_key_exists('access_specific_zones', $user_capabilities[$_SESSION['module']]) && !array_key_exists('view_all', $user_capabilities[$_SESSION['module']]) && $user_capabilities[$_SESSION['module']]['access_specific_zones'][0]) ? 'AND domain_id IN (' . join(',', $this->getZoneAccessIDs($user_capabilities[$_SESSION['module']]['access_specific_zones'])) . ')' : null;
+			$limited_ids = (array_key_exists('access_specific_zones', (array) $user_capabilities[$_SESSION['module']]) && !array_key_exists('view_all', $user_capabilities[$_SESSION['module']]) && $user_capabilities[$_SESSION['module']]['access_specific_zones'][0]) ? 'AND domain_id IN (' . join(',', $this->getZoneAccessIDs($user_capabilities[$_SESSION['module']]['access_specific_zones'])) . ')' : null;
 		}
 		basicGet('fm_' . $__FM_CONFIG[$_SESSION['module']]['prefix'] . 'domains', $domain_id, 'domain_', 'domain_clone_domain_id', $limited_ids . ' AND domain_template="no" ORDER BY domain_name');
 		if ($fmdb->num_rows) {
diff -ur ./fm-modules/fmDNS/pages/zone-records-validate.php /var/www/html/facileManager/fm-modules/fmDNS/pages/zone-records-validate.php
--- ./fm-modules/fmDNS/pages/zone-records-validate.php	2022-09-24 10:13:32.114742774 -0700
+++ /var/www/html/facileManager/fm-modules/fmDNS/pages/zone-records-validate.php	2022-09-24 10:39:41.001217635 -0700
@@ -133,11 +133,11 @@
 		if (is_array($value[$id])) $value[$id]['action'] = $action;
 	}
 	
-	if (array_key_exists('soa_template_chosen', $value)) {
+	if (array_key_exists('soa_template_chosen', (array) $value)) {
 		unset($value['soa_template_chosen']);
 	}
 	foreach ($value as $id => $array) {
-		if (count($input_error[$id]['errors'])) {
+		if (count((array)$input_error[$id]['errors'])) {
 			$img = $__FM_CONFIG['icons']['fail'];
 			$action = __('None');
 		} else {
@@ -265,7 +265,7 @@
 				}
 			}
 			
-			if (!count($messages['errors'])) {
+			if (!count((array)$messages['errors'])) {
 				$html .= buildInputReturn($action, $id, $key, $val);
 			} else $html = null;
 		}
diff -ur ./fm-modules/fmDNS/pages/zones.php /var/www/html/facileManager/fm-modules/fmDNS/pages/zones.php
--- ./fm-modules/fmDNS/pages/zones.php	2022-09-24 10:13:32.114742774 -0700
+++ /var/www/html/facileManager/fm-modules/fmDNS/pages/zones.php	2022-09-24 09:57:42.842850940 -0700
@@ -152,7 +152,7 @@
 	$user_capabilities = getUserCapabilities($_SESSION['user']['id'], 'all');
 
 	$limited_domain_ids = ')';
-	if (array_key_exists('access_specific_zones', $user_capabilities[$_SESSION['module']]) && !array_key_exists('view_all', $user_capabilities[$_SESSION['module']]) && $user_capabilities[$_SESSION['module']]['access_specific_zones'][0]) {
+	if (array_key_exists('access_specific_zones', (array) $user_capabilities[$_SESSION['module']]) && !array_key_exists('view_all', $user_capabilities[$_SESSION['module']]) && $user_capabilities[$_SESSION['module']]['access_specific_zones'][0]) {
 		$limited_domain_ids = "OR domain_clone_domain_id>0) AND domain_id IN (";
 		$limited_domain_ids .= join(',', $fm_dns_zones->getZoneAccessIDs($user_capabilities[$_SESSION['module']]['access_specific_zones'])) . ')';
 	}
diff -ur ./fm-modules/fmDNS/variables.inc.php /var/www/html/facileManager/fm-modules/fmDNS/variables.inc.php
--- ./fm-modules/fmDNS/variables.inc.php	2022-09-24 10:13:32.118742790 -0700
+++ /var/www/html/facileManager/fm-modules/fmDNS/variables.inc.php	2022-09-23 19:16:58.417988792 -0700
@@ -28,6 +28,7 @@
  */
 
 if (!@is_array($__FM_CONFIG)) $__FM_CONFIG = array();
+if (!@is_array($__FM_CONFIG['icons'])) $__FM_CONFIG['icons'] = array();
 
 /** Module Information */
 $__FM_CONFIG['fmDNS'] = array(

```

**Comment by sidantaa** [comment]
Hi @gianlucagiacometti,

I tried downgrading my PHP version to 7.4.33 but still i am getting this issue:

[Sat Dec 24 20:12:40.903743 2022] [proxy_fcgi:error] [pid 9290] [client 10.35.35.16:52315] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: sort(): Argument #1 ($array) must be of type array, null given in /var/www/html/dnsadmin/fm-modules/facileManager/variables.inc.php:109\nStack trace:\n#0 /var/www/html/dnsadmin/fm-modules/facileManager/variables.inc.php(109): sort()\n#1 /var/www/html/dnsadmin/fm-modules/facileManager/functions.php(71): include('...')\n#2 /var/www/html/dnsadmin/fm-includes/init.php(30): require_once('...')\n#3 /var/www/html/dnsadmin/fm-install.php(47): require_once('...')\n#4 {main}\n  thrown in /var/www/html/dnsadmin/fm-modules/facileManager/variables.inc.php on line 109'

**Comment by andrewhotlab** [comment]
Just hit this problem by upgrading to the latest FreeBSD Ports quarterly branch... since I have zero competence on PHP and programming in general, the only way I guess can contribute with is to sponsor the work of someone. If anyone is interested, you can contact me directly via email. Thanks!

**Comment by WillyXJ** [comment]
Commit added to the [master-prerelease-bugfixes](https://github.com/WillyXJ/facileManager/compare/master-prerelease-bugfixes) branch for PHP 8.2 support. Use at your own risk or wait until it's included in an official release.

**Comment by gianlucagiacometti** [comment]
Thank you @WillyXJ 

@sidantaa , I downgraded to 7.4.33, too, and everything went fine with no changing in the released code

**Comment by WillyXJ** [comment]
Additional commits have been added to https://github.com/WillyXJ/facileManager/compare/master-prerelease-bugfixes containing more PHP 8 fixes as all modules and functionality is getting regression-tested.

**Comment by andrewhotlab** [comment]
Sorry, only today I get the chance to try your latest commits. Creating, modifying and deleting forward zones and resource records is OK now: thanks @WillyXJ !
I'll try to test it more in the following days, but as for now it looks like good for production to me (I'm running PHP 8.0).

**Comment by WillyXJ** [comment]
This is now supported in [fM 4.4.0](http://www.facilemanager.com/download/) and later.
