### ISSUE TITLE
"DNS Servers": Uncaught Error: [] operator not supported for strings in /srv/www/v10005/docroot/httpdocs/fm-modules/fmDNS/functions.php:694

### ISSUE THREAD

**Issue by internethering** [WillyXJ/facileManager#624]
`Fatal error: Uncaught Error: [] operator not supported for strings in /srv/www/v10005/docroot/httpdocs/fm-modules/fmDNS/functions.php:694 Stack trace: #0 /srv/www/v10005/docroot/httpdocs/fm-modules/fmDNS/classes/class_zones.php(461): getZoneServers() #1 /srv/www/v10005/docroot/httpdocs/fm-modules/fmDNS/pages/templates-zones.php(42): fm_dns_zones->update() #2 /srv/www/v10005/docroot/httpdocs/index.php(57): include('...') #3 {main} thrown in /srv/www/v10005/docroot/httpdocs/fm-modules/fmDNS/functions.php on line 694`

When I try to edit the field "DNS Servers" in my zone templates.

Same error, If I edit the field "DNS Servers" in forward zones:

`Fatal error: Uncaught Error: [] operator not supported for strings in /srv/www/v10005/docroot/httpdocs/fm-modules/fmDNS/functions.php:694 Stack trace: #0 /srv/www/v10005/docroot/httpdocs/fm-modules/fmDNS/classes/class_zones.php(461): getZoneServers() #1 /srv/www/v10005/docroot/httpdocs/fm-modules/fmDNS/pages/zones.php(61): fm_dns_zones->update() #2 /srv/www/v10005/docroot/httpdocs/fm-modules/fmDNS/pages/zones-forward.php(27): include('/srv/www/v10005...') #3 /srv/www/v10005/docroot/httpdocs/index.php(57): include('/srv/www/v10005...') #4 {main} thrown in /srv/www/v10005/docroot/httpdocs/fm-modules/fmDNS/functions.php on line 694`

**Comment by internethering** [comment]
duplicate #622
