### ISSUE TITLE
[BUG] Reverse zone edit: Uncaught TypeError: explode(): Argument #2 ($string) must be of type string

### ISSUE THREAD

**Issue by imyller** [WillyXJ/facileManager#629]
fM Version : **4.6.2**
fmDNS Version : **6.0.5**

Debian 12 (Bookworm)
PHP 8.2.18
Apache 2.4.59

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/WillyXJ/facileManager/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/WillyXJ/facileManager/issues?q=is%3Aissue+is%3Aclosed) and [opened issues](https://github.com/WillyXJ/facileManager/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

---

**(BUG | ISSUE) Expected Behavior:**

Zone edit works.

**(BUG | ISSUE) Actual Behavior:**

`Fatal error: Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, array given in /opt/facileManager/server/fm-modules/fmDNS/classes/class_records.php:923 Stack trace: #0 /opt/facileManager/server/fm-modules/fmDNS/classes/class_records.php(923): explode() #1 /opt/facileManager/server/fm-modules/fmDNS/ajax/getData.php(283): fm_dns_records->getServerZoneData() #2 /opt/facileManager/server/fm-modules/facileManager/ajax/getData.php(143): include('...') #3 {main} thrown in /opt/facileManager/server/fm-modules/fmDNS/classes/class_records.php on line 923`

Click zone to edit records:

<img width="1046" alt="editerr1" src="https://github.com/WillyXJ/facileManager/assets/1898870/05bd9add-ef34-4cfb-9b4d-6131234681f1">

Results in:

<img width="1161" alt="editerr3" src="https://github.com/WillyXJ/facileManager/assets/1898870/ec4948b3-f7e5-4bbf-a4b4-45a20e6d663e">

**(BUG | ISSUE) Steps to reproduce:**

* Fresh installation
* Create server configuration
* Assign reverse zone DNS servers 'All servers' (default)
* Edit reverse zone
* Fatal PHP error is displayed

**Comment by imyller** [comment]
Fix caused regression:
https://github.com/WillyXJ/facileManager/issues/630#issuecomment-2176274169
